# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6dbf3dd5fffee86d6e4c733b42b0d4e87085d8c478fce267fc9a565ce8db94b1520b7a6f9af258d0784eec779abad46dd92e22311c8b5bbe86ee3d122a25986

test:
  secret_key_base: c27c76b87178b871d4068f6f62039008e4276e3ba9c675c62066cb82a8cfa4d5e50d4630f2e13c888b4bae475b5168555e8de2784d73a3c30c1cd99477d89572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
